name: cuda-cross-build

on: [push]

jobs:
  windows_opencl:
    name: opencl/release/windows
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW
      run: |
        sudo apt update
        sudo apt install mingw-w64

    - name: build
      run: |
        x86_64-w64-mingw32-dlltool -d cl/opencl.def -D OpenCL.dll -l cl/OpenCL.lib

        x86_64-w64-mingw32-g++ -o ${{ github.event.repository.name }}-opencl.exe opencl_main.cpp \
          -D_WIN64 -DWIN64 -D_WIN32 -DWIN32 \
          -Iboinc \
          -Lboinc/lib/win \
          -static-libgcc -static-libstdc++ \
          -lboinc_api -lboinc_opencl -lboinc \
          -Lcl -lOpenCL
    - uses: actions/upload-artifact@v4
      with:
       name: ${{ github.event.repository.name }}-opencl-win.exe
       path: ./${{ github.event.repository.name }}-opencl*